// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {commandrunner} from '../models';
import {bindings} from '../models';
import {commandhistory} from '../models';
import {context} from '../models';

export function CancelCommand():Promise<void>;

export function Close():Promise<void>;

export function CompletePath(arg1:string):Promise<commandrunner.CompletionResult>;

export function Connect(arg1:string):Promise<commandrunner.ConnectResult>;

export function DeleteHistory(arg1:string):Promise<void>;

export function InitialState():Promise<bindings.CommandInitialState>;

export function RunCommand(arg1:string):Promise<commandhistory.Entry>;

export function SetContext(arg1:context.Context):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;
