// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelCommand() {
  return window['go']['bindings']['CommandBindings']['CancelCommand']();
}

export function Close() {
  return window['go']['bindings']['CommandBindings']['Close']();
}

export function CompletePath(arg1) {
  return window['go']['bindings']['CommandBindings']['CompletePath'](arg1);
}

export function Connect(arg1) {
  return window['go']['bindings']['CommandBindings']['Connect'](arg1);
}

export function DeleteHistory(arg1) {
  return window['go']['bindings']['CommandBindings']['DeleteHistory'](arg1);
}

export function InitialState() {
  return window['go']['bindings']['CommandBindings']['InitialState']();
}

export function RunCommand(arg1) {
  return window['go']['bindings']['CommandBindings']['RunCommand'](arg1);
}

export function SetContext(arg1) {
  return window['go']['bindings']['CommandBindings']['SetContext'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['bindings']['CommandBindings']['Shutdown'](arg1);
}
