// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['bindings']['ExplorerBindings']['Close']();
}

export function Connect(arg1) {
  return window['go']['bindings']['ExplorerBindings']['Connect'](arg1);
}

export function Copy(arg1, arg2) {
  return window['go']['bindings']['ExplorerBindings']['Copy'](arg1, arg2);
}

export function CreateFolder(arg1, arg2) {
  return window['go']['bindings']['ExplorerBindings']['CreateFolder'](arg1, arg2);
}

export function Delete(arg1) {
  return window['go']['bindings']['ExplorerBindings']['Delete'](arg1);
}

export function Download(arg1) {
  return window['go']['bindings']['ExplorerBindings']['Download'](arg1);
}

export function InitialState() {
  return window['go']['bindings']['ExplorerBindings']['InitialState']();
}

export function ListDirectory(arg1) {
  return window['go']['bindings']['ExplorerBindings']['ListDirectory'](arg1);
}

export function Move(arg1, arg2) {
  return window['go']['bindings']['ExplorerBindings']['Move'](arg1, arg2);
}

export function PreviewFile(arg1) {
  return window['go']['bindings']['ExplorerBindings']['PreviewFile'](arg1);
}

export function Rename(arg1, arg2) {
  return window['go']['bindings']['ExplorerBindings']['Rename'](arg1, arg2);
}

export function SaveFile(arg1, arg2, arg3) {
  return window['go']['bindings']['ExplorerBindings']['SaveFile'](arg1, arg2, arg3);
}

export function SetContext(arg1) {
  return window['go']['bindings']['ExplorerBindings']['SetContext'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['bindings']['ExplorerBindings']['Shutdown'](arg1);
}

export function Upload(arg1, arg2, arg3) {
  return window['go']['bindings']['ExplorerBindings']['Upload'](arg1, arg2, arg3);
}
