// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {remote} from '../models';
import {bindings} from '../models';
import {context} from '../models';

export function Close():Promise<void>;

export function Connect(arg1:string):Promise<remote.ConnectResult>;

export function Download(arg1:Array<string>):Promise<Array<string>>;

export function InitialState():Promise<bindings.ExplorerInitialState>;

export function ListDirectory(arg1:string):Promise<remote.Directory>;

export function PreviewFile(arg1:string):Promise<remote.Preview>;

export function SaveFile(arg1:string,arg2:string,arg3:string):Promise<remote.Preview>;

export function SetContext(arg1:context.Context):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;
