// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['bindings']['ExplorerBindings']['Close']();
}

export function Connect(arg1) {
  return window['go']['bindings']['ExplorerBindings']['Connect'](arg1);
}

export function Download(arg1) {
  return window['go']['bindings']['ExplorerBindings']['Download'](arg1);
}

export function InitialState() {
  return window['go']['bindings']['ExplorerBindings']['InitialState']();
}

export function ListDirectory(arg1) {
  return window['go']['bindings']['ExplorerBindings']['ListDirectory'](arg1);
}

export function PreviewFile(arg1) {
  return window['go']['bindings']['ExplorerBindings']['PreviewFile'](arg1);
}

export function SaveFile(arg1, arg2, arg3) {
  return window['go']['bindings']['ExplorerBindings']['SaveFile'](arg1, arg2, arg3);
}

export function SetContext(arg1) {
  return window['go']['bindings']['ExplorerBindings']['SetContext'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['bindings']['ExplorerBindings']['Shutdown'](arg1);
}
