// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['bindings']['HostBindings']['Close']();
}

export function DeletePortLink(arg1) {
  return window['go']['bindings']['HostBindings']['DeletePortLink'](arg1);
}

export function DiscoverPorts(arg1) {
  return window['go']['bindings']['HostBindings']['DiscoverPorts'](arg1);
}

export function FindPortFavicon(arg1, arg2) {
  return window['go']['bindings']['HostBindings']['FindPortFavicon'](arg1, arg2);
}

export function InitialState() {
  return window['go']['bindings']['HostBindings']['InitialState']();
}

export function OpenPort(arg1, arg2) {
  return window['go']['bindings']['HostBindings']['OpenPort'](arg1, arg2);
}

export function SavePortLink(arg1) {
  return window['go']['bindings']['HostBindings']['SavePortLink'](arg1);
}

export function SetContext(arg1) {
  return window['go']['bindings']['HostBindings']['SetContext'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['bindings']['HostBindings']['Shutdown'](arg1);
}
