// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {browser} from '../models';
import {bindings} from '../models';
import {session} from '../models';
import {config} from '../models';
import {portlink} from '../models';
import {server} from '../models';
import {context} from '../models';

export function Close():Promise<void>;

export function DeleteConnectionConfiguration(arg1:string):Promise<void>;

export function DeletePortLink(arg1:string):Promise<void>;

export function DeleteServer(arg1:string):Promise<void>;

export function DiscoverBrowsers():Promise<Array<browser.BrowserOption>>;

export function DiscoverPorts(arg1:string):Promise<bindings.HostPortDiscoveryResult>;

export function FindPortFavicon(arg1:number,arg2:string):Promise<bindings.HostFaviconResult>;

export function InitialState():Promise<bindings.HostInitialState>;

export function LaunchBrowserThroughSocks(arg1:string,arg2:string):Promise<void>;

export function ListRuntimeSessions():Promise<Array<session.RuntimeSession>>;

export function ListSessionHistory(arg1:string):Promise<Array<session.SessionHistoryEntry>>;

export function LoadAppState():Promise<bindings.LoadInitialStateResult>;

export function OpenPort(arg1:number,arg2:string):Promise<bindings.HostOpenPortResult>;

export function PreviewBrowserLaunchThroughSocks(arg1:string,arg2:string):Promise<browser.LaunchPreview>;

export function RetryConfiguration(arg1:string):Promise<session.RuntimeSession>;

export function SaveConnectionConfiguration(arg1:config.ConnectionConfiguration):Promise<config.ConnectionConfiguration>;

export function SavePortLink(arg1:portlink.Link):Promise<portlink.Link>;

export function SaveServer(arg1:server.Server):Promise<server.Server>;

export function SetContext(arg1:context.Context):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function StartConfiguration(arg1:string):Promise<session.RuntimeSession>;

export function StartServerConfigurations(arg1:string):Promise<Array<session.RuntimeSession>>;

export function StopConfiguration(arg1:string):Promise<session.RuntimeSession>;

export function SubmitKeyUnlock(arg1:string,arg2:string):Promise<session.RuntimeSession>;
