// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bindings} from '../models';
import {portlink} from '../models';
import {context} from '../models';

export function Close():Promise<void>;

export function DeletePortLink(arg1:string):Promise<void>;

export function DiscoverPorts(arg1:string):Promise<bindings.HostPortDiscoveryResult>;

export function FindPortFavicon(arg1:number,arg2:string):Promise<bindings.HostFaviconResult>;

export function InitialState():Promise<bindings.HostInitialState>;

export function OpenPort(arg1:number,arg2:string):Promise<bindings.HostOpenPortResult>;

export function SavePortLink(arg1:portlink.Link):Promise<portlink.Link>;

export function SetContext(arg1:context.Context):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;
