// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Focus(arg1) {
  return window['go']['bindings']['PreviewLauncherBindings']['Focus'](arg1);
}

export function Open(arg1) {
  return window['go']['bindings']['PreviewLauncherBindings']['Open'](arg1);
}

export function State(arg1) {
  return window['go']['bindings']['PreviewLauncherBindings']['State'](arg1);
}
