// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {remote} from '../models';
import {bindings} from '../models';
import {context} from '../models';

export function Connect(arg1:string):Promise<remote.ConnectResult>;

export function InitialState():Promise<bindings.PreviewInitialState>;

export function PreviewFile():Promise<remote.Preview>;

export function SetContext(arg1:context.Context):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;
