// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {previewwindow} from '../models';

export function Focus(arg1:string):Promise<previewwindow.State>;

export function Open(arg1:string):Promise<previewwindow.State>;

export function State(arg1:string):Promise<previewwindow.State>;
