// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['bindings']['PreviewBindings']['Connect'](arg1);
}

export function InitialState() {
  return window['go']['bindings']['PreviewBindings']['InitialState']();
}

export function PreviewFile() {
  return window['go']['bindings']['PreviewBindings']['PreviewFile']();
}

export function SetContext(arg1) {
  return window['go']['bindings']['PreviewBindings']['SetContext'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['bindings']['PreviewBindings']['Shutdown'](arg1);
}
