// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AllowClose() {
  return window['go']['bindings']['SettingsWindowBindings']['AllowClose']();
}

export function IsSettingsWindow() {
  return window['go']['bindings']['SettingsWindowBindings']['IsSettingsWindow']();
}

export function RequestCloseConfirmation() {
  return window['go']['bindings']['SettingsWindowBindings']['RequestCloseConfirmation']();
}
