// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AllowClose():Promise<void>;

export function IsSettingsWindow():Promise<boolean>;

export function RequestCloseConfirmation():Promise<boolean>;
